import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Alert from "@/Alert";
import Header from "@/Header";
import Footer from "@/Footer";
import NewsLetter from "@/NewsLetter";

const satoshi = localFont({
  src: "./fonts/Satoshi-Variable.woff2",
  display: "swap",
  variable: "--font-satoshi",
});

const integralCF = localFont({
  src: "./fonts/integralcf-bold.otf",
  display: "swap",
  variable: "--font-integral",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${integralCF.variable} antialiased`}
      >
        <div className="w-full">
          <Alert />
          <Header />
          {children}
          {/* <div className="relative">
            <NewsLetter />
            <Footer />
          </div> */}
        </div>
      </body>
    </html>
  );
}
